apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platform-splashpage.fullname" . }}
  labels:
    {{- include "platform-splashpage.labels" . | nindent 4 }}
data:
  app.json: |
    {{- include "platform-splashpage.appJson" . | fromYaml | toJson | nindent 4 }}