version: '3.9'
services:
  keycloak:
    networks:
      - local-keycloak
    image: quay.io/keycloak/keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
    ports:
    - 8080:8080
  splash:
    networks:
      - local-keycloak
    build:
      context: .
    env_file:
      - .env.local
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=say_lalisa_love_me_lalisa_love_me_hey
      - SPLASH_APP_DIR=/config/app.json
    ports:
    - 3000:80
    volumes:
      - ./config:/config
      - ./public:/app/public
networks:
  local-keycloak: