apiVersion: v2
name: platform-splashpage
description: A Helm chart for Simple Platform Splashpages
type: application
version: 0.0.1 # set by ci
appVersion: "0.0.1" # set by ci
dependencies:
  - name: common
    repository: "@skyfjell"
    version: "0.0.x"
